<?php
namespace backend\models\form;

use common\components\behaviors\RbacLog;
use Yii;
use yii\base\Event;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use common\models\data\Maintain as MaintainModel;
use common\components\events\SearchEvent;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
/**
 * Maintain represents the model behind the search form of `common\models\data\Maintain`.
 */
class Rbac extends Model
{

    const RBAC_METHOD_GET='GET';
    const RBAC_METHOD_POST='POST';
    public static $method_code=['GET'=>'get','POST'=>'post'];

    public $name;

    public $type;

    public $description;

    public $ruleName;

    public $data;


    public $route;

    public $method;

    public $group;

    public $category;

    public $sort;


    public $permissions;

    public $roles;


    const EVENT_AFTER_CREATE='afterCreate';
    const EVENT_AFTER_UPDATE='afterUpdate';
    const EVENT_AFTER_DELETE='afterDelete';

    /**
     * @inheritdoc
     */

    public function rules()
    {
        return [
            [['route', 'method', 'description', 'group', 'category'], 'required', 'on' => 'permission'],
            [['sort'], 'number', 'on'=>['role', 'permission']],
            [['sort'], 'default', 'value'=>0, 'on'=>['role', 'permission']],
            [
                ['route'],
                'match',
                'pattern' => '/^[\/].*/',
                'message' => yii::t('app', yii::t('app', 'Must begin with "/" like "/module/controller/action" format')),
                'on' => 'permission'
            ],

            [['name', 'description'], 'required', 'on' => 'role'],
            [['roles', 'permissions'], 'default', 'on' => 'role'],
        ];
    }

    public function behaviors()
    {
        return [
            'log'=>[
                'class'=>RbacLog::className(),
            ],
        ]; // TODO: Change the autogenerated stub
    }

    public function scenarios()
    {
        return [
            'permission' => ['route', 'method', 'description', 'sort', 'group', 'category'],
            'role' => ['name', 'description', 'sort', 'roles', 'permissions']
        ];
    }

    public function attributeLabels()
    {
        return [
            "route" => yii::t('model', 'Route'),
            "method" => yii::t('model', 'HTTP Method'),
            "description" => yii::t('model', 'Description'),
            "group" => yii::t('model', 'Group'),
            "category" => yii::t('model', 'Category'),
            "sort" => yii::t('model', 'Sort'),
            "name" => yii::t('model', 'Role'),
            "permissions" => yii::t('model', 'Permissions'),
            "roles" => yii::t('model', 'Role'),
        ];
    }

    public function createPermission()
    {
        $this->name = $this->route . ':' . $this->method;
        $authManager = yii::$app->getAuthManager();
        if ($authManager->getPermission($this->name) !== null) {
            $this->addError('route', yii::t('model', 'Permission exists'));
            $this->addError('method', yii::t('model', 'Permission exists'));
            return false;
        }
        $permission = $authManager->createPermission($this->name);
        $permission->description = $this->description;
        $permission->data = json_encode([
            'group' => $this->group,
            'sort' => $this->sort,
            'category' => $this->category,
        ]);
        if( $authManager->add($permission) ){
            $this->trigger(self::EVENT_AFTER_CREATE,new Event());
            return true;
        }
        return false;
    }

    public function updatePermission($name)
    {
        $oldModel = clone $this;
        $oldModel->fillModel($name);
        $this->name = $this->route . ':' . $this->method;
        $authManager = yii::$app->getAuthManager();
        $permission = $authManager->getPermission($name);
        if( $permission->name != $name ){//修改权限名称
            if( $authManager->getPermission($name) !== null ){
                $this->addError('route', yii::t('model', 'Permission exists'));
                $this->addError('method', yii::t('model', 'Permission exists'));
                return false;
            }
        }
        $permission->name = $this->name;
        $permission->description = $this->description;
        $permission->data = json_encode([
            'group' => $this->group,
            'sort' => $this->sort,
            'category' => $this->category,
        ]);
        if( $authManager->update($name, $permission) ){
            $this->trigger(self::EVENT_AFTER_UPDATE,new Event());
            return true;
        }
        return false;
    }

    public function deletePermission()
    {
        $authManager = yii::$app->getAuthManager();
        $permission = $authManager->getPermission($this->name);
        if( $authManager->remove($permission) ){
            if( $authManager->add($permission) ){
                $this->trigger(self::EVENT_AFTER_DELETE,new Event());
                return true;
            }
            return true;
        }
        return false;
    }


    public function createRole()
    {
        $authManager = yii::$app->getAuthManager();
        if ($authManager->getRole($this->name) !== null) {
            $this->addError('name', yii::t('app', 'Role exists'));
            return false;
        }
        $role = $authManager->createRole($this->name);
        $role->description = $this->description;
        $role->data = json_encode([
            'sort' => $this->sort,
        ]);
        if( $authManager->add($role) ){
            if( $this->permissions === null ) $this->permissions = [];
            $this->permissions = array_flip($this->permissions);
            if (isset($this->permissions[0])) unset($this->permissions[0]);
            $this->permissions = array_flip($this->permissions);
            foreach ($this->permissions as $permission){
                $permission = $authManager->getPermission($permission);
                $authManager->addChild($role, $permission);
            }
            $this->trigger(self::EVENT_AFTER_CREATE,new Event());
            return true;
        }
        return false;
    }

    public function updateRole($name)
    {
        $oldModel = clone $this;
        $oldModel->fillModel($name);

        $authManager = yii::$app->getAuthManager();
        $role = $authManager->getRole($name);
        if( $role->name != $this->name ){//修改角色名称
            if( $authManager->getRole($this->name) !== null ){
                $this->addError('name', yii::t('app', 'Role exists'));
                return false;
            }
        }
        $role->name = $this->name;
        $role->description = $this->description;
        $role->data = json_encode([
            "sort" => $this->sort,
        ]);

        $oldPermissions = array_keys( $authManager->getPermissionsByRole($name) );

        if( $authManager->update($name, $role) ){
            if( $this->permissions === null ) $this->permissions = [];
            $this->permissions = array_flip($this->permissions);
            if (isset($this->permissions[0])) unset($this->permissions[0]);
            $this->permissions = array_flip($this->permissions);

            $needAdds = array_diff($this->permissions, $oldPermissions);
            foreach ($needAdds as $permission){
                $permission = $authManager->getPermission($permission);
                $authManager->addChild($role, $permission);
            }

            $needRemoves = array_diff($oldPermissions, $this->permissions);
            foreach ($needRemoves as $permission){
                $permission = $authManager->getPermission($permission);
                $authManager->removeChild($role, $permission);
            }

            $this->trigger(self::EVENT_AFTER_UPDATE,new Event());
            return true;
        }
        return false;

    }

    public function deleteRole()
    {
        $authManager = yii::$app->getAuthManager();
        $role = $authManager->getRole($this->name);
        if ($authManager->remove($role)) {
            $this->trigger(self::EVENT_AFTER_DELETE,new Event());
            return true;
        } else {
            return false;
        }
    }

    public function getPermissionsByGroup($type='index')
    {
        $authManager = yii::$app->getAuthManager();
        $fillDatas = [];
        $originPermissions = $authManager->getPermissions();

        $permissions = [];
        foreach ($originPermissions as $originPermission){
            $data = json_decode($originPermission->data, true);
            $temp = explode(":", $originPermission->name);
            $permissions[] = [
                'name' => $originPermission->name,
                'route' => $temp[0],
                'method' => $temp[1],
                'description' => $originPermission->description,
                'group' => $data['group'],
                'category' => $data['category'],
                'sort' => $data['sort'],
            ];
        }
        ArrayHelper::multisort($permissions, 'sort');
        foreach ($permissions as $permission){
            $fillDatas[$permission['group']][$permission['category']][] = $permission;
        }
        $return = [];
        if( $type == 'index' ){
            foreach ($fillDatas as $value){
                foreach ($value as $val) {
                    foreach ($val as $v) {
                        $return[] = new self(array_merge($v, ['scenario' => 'role']));
                    }
                }
            }
        }else{
            $return = $fillDatas;
        }
        return $return;
    }

    public function getRoles()
    {
        $authManager = yii::$app->getAuthManager();
        $originRoles = $authManager->getRoles();

        $fillDatas = [];
        foreach ($originRoles as $originRole){
            $data = json_decode($originRole->data, true);
            $fillDatas[] = [
                'name' => $originRole->name,
                'description' => $originRole->description,
                'sort' => $data['sort'],
            ];
        }

        ArrayHelper::multisort($fillDatas, 'sort');

        $return = [];
        foreach ($fillDatas as $fillData){

            $return[] = new self(array_merge($fillData, ['scenario'=>'role']));
        }
        return $return;
    }

    public function fillModel($name)
    {
        $authManager = yii::$app->getAuthManager();
        if( $this->getScenario() == 'permission' ){
            $permission = $authManager->getPermission($name);
            if( $permission === null ) throw new NotFoundHttpException("Cannot find permission $name");
            $data = json_decode($permission->data, true);
            $temp = explode(":", $permission->name);
            $this->name = $permission->name;
            $this->route = $temp[0];
            $this->method = $temp[1];
            $this->description = $permission->description;
            $this->group = $data['group'];
            $this->category = isset( $data['category'] ) ? $data['category'] : '';
            $this->sort = $data['sort'];
        }else{
            $role = $authManager->getRole($name);
            $data = json_decode($role->data, true);
            $temp = $authManager->getPermissionsByRole($role->name);
            $permissions = [];
            foreach ($temp as $permission){
                $permissions[$permission->name] = $permission->name;
            }
            $this->name = $role->name;
            $this->description = $role->description;
            $this->sort = $data['sort'];
            $this->permissions = $permissions;
            $this->roles = array_keys( $authManager->getChildRoles($role->name) );
        }
    }

    public function getGroups()
    {
        $temp = $this->getPermissionsByGroup();
        $groups = [];
        foreach ($temp as $v){
            $groups[$v->group] = $v->group;
        }
        return $groups;
    }

    public function getCategories()
    {
        $temp = $this->getPermissionsByGroup();
        $categories = [];
        foreach ($temp as $v){
            $categories[$v->category] = $v->category;
        }
        return $categories;
    }
}
