<?php
/**
 * Author: lf
 * Blog: https://blog.feehi.com
 * Email: job@feehi.com
 * Created at: 2017-12-03 22:05
 */

namespace backend\models\form;

use common\models\data\Options;
use yii;
use yii\db\ActiveRecord;
use yii\behaviors\AttributeBehavior;
class SettingBannerForm extends Options
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(),[
            'banner'=>[
                'class' =>AttributeBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_VALIDATE =>'type',
                ],
                'value'=>self::OPTIONS_TYPE_BANNER,
            ],
        ]); // TODO: Change the autogenerated stub
    }
}