<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/7
 * Time: 21:20
 */

namespace backend\components\widget;


use common\models\data\AdminMessage;
use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\Url;

class MessageWidget extends Widget
{

    public $count;
    public $msgUrl;
    public $aOption=[];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($this->aOption['id'])){
            $this->aOption['id']='message-item-a';
        }
        if($this->msgUrl==null){
            $this->msgUrl=Url::to(['/admin/message/box']);
        }
    }

    public function run()
    {
        echo $this->renderMessage();
        $this->renderLiJs();
    }

    public static $messageLeve_code=[0=>'success',1=>'success',2=>'info',3=>'warning',4=>'danger'];

    public function renderMessage(){
        $count=AdminMessage::getMessageCount(\yii::$app->user->id);
        return $this->renderCount($count,$this->aOption)."<ul class=\"dropdown-menu notifications\" id=\"message-box-li\"></ul>";
    }

    public function renderCount($count,$option=[]){
        $option=array_merge($option,[
            'class'=>"dropdown-toggle",'data-toggle'=>"dropdown", 'aria-expanded'=>false,
        ]);

        return Html::a(Html::tag('i','',['class'=>'lnr lnr-alarm']).Html::tag('span',$count,['class'=>'badge bg-danger']),'#',$option);
    }

    public function renderLiJs(){

        $urlItem=Url::to(['/admin/message/view']);
        $urlMore=Url::to(['/admin/message/index']);
        if(empty($aOption['class'])){
            $aOption['class']='notification-item';
        }
        $moreMsg=\yii::t('app','More Messages');
        $errMsg=\yii::t('app','Error Get Messages');
        \yii::$app->view->registerJs(<<<SCRIPT
        $('#{$this->aOption['id']}').click(function(){
            $('#message-box-li').html('');
            $.ajax({
                url:'{$this->msgUrl}',
                type:'get',
                dataType:'json',
                success:function(res){                                 
                    if(res.status){                  
                        listMsg(res.data);
                    }
                    $('#message-box-li').append("<li><a href=\"{$urlMore}\">{$moreMsg}</li>");
                },
                error:function(){
                    $('#message-box-li').append("<li><a href=\"{$urlMore}\">{$moreMsg}</li>");
                }
            })
        });
        function listMsg(data){
            var level_css=['success','success','info','warning','danger'];
            var li='';
            if(typeof data =="object"){
                $(data).each(function(k,v){
                    li='<li><a href="{$urlItem}?id='+v['id']+'"><span class=\"dot bg-'+(level_css[v['level']]||'danger')+'\"></span>'+v['name']+'</a></li>';
                    $('#message-box-li').append(li);
                });
            }
        }
        
SCRIPT
);
    }
}