<?php

namespace common\models\crud;

use Yii;
use common\models\data\ArticleCate as ArticleCateModel;

/**
 * ArticleCate represents the model behind the search form about `common\models\data\ArticleCate`.
 */
class ArticleCate extends ArticleCateModel
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        $rules=[
            [['name'],'required'],
            [['parent_id',],'validateIn','message'=>Yii::t('app','父级选择错误'),'skipOnEmpty'=>true],
        ];
        return array_merge($rules,parent::rules());
    }

    public function validateIn($attribute, $params){
        if(!(self::find()->where(['id'=>$this->$attribute])->exists())){
            $this->addError($attribute, Yii::t('app','无父级'));
        }
    }

    public function beforeSave($insert)
    {

        if(!empty($this->parent_id)){
            $model=self::find()->select('id,level,path')->one();
            $this->level=$model['level']+1;
            $this->path=$model['path'].','.$model['id'];
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
