<?php

namespace common\models\crud;

use Yii;
use common\models\data\Article as ArticleModel;

/**
 * Article represents the model behind the search form about `common\models\data\Article`.
 */
class Article extends ArticleModel
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        $rules=[
            [['title','content','cate_id'],'required'],
        ];
        return array_merge($rules,parent::rules());
    }

    public function getCate()
    {
        return $this->hasOne(ArticleCate::className(), ['id' => 'cate_id']);
    }

    public function beforeSave($insert)
    {
        $this->remain=$insert==true?0:1;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
