<?php
namespace backend\modules\admin\controllers;

use backend\components\actions\UploadAction;
use backend\controllers\CommonController;
use common\components\tools\ModelHelper;
use common\models\data\Admin;
use common\models\data\AdminInfo;
use common\models\tool\UploadImg;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends CommonController
{

    public function actions()
    {
        return [
            'upload'=>[
                'class' => UploadAction::className(),
                'imgClass'=>UploadImg::className(),
                'imgConfig'=>['imgServerPath'=>'@backend/web/upload/']
            ],
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     */
    public function actionIndex()
    {
        $request=\yii::$app->request;
        $admin=Admin::findOne(\yii::$app->user->id);
        $info=AdminInfo::find()->where(['admin_id'=>$admin->id])->one();
        if($admin && $info){
            if($request->isPost ){

                $t=\yii::$app->db->beginTransaction();
                if( !($admin->load($request->post()) && $admin->save())){
                    $err=ModelHelper::getErrorAsString($admin->getErrors());
                    $t->rollBack();
                }
                $info->admin_id=$admin->id;
                if( !($info->load($request->post()) && $info->save()) ){
                    $err=ModelHelper::getErrorAsString($info->getErrors());
                    $t->rollBack();
                }
                if($request->isAjax){
                    if(isset($err)){
                        return ['status'=>false,'msg'=>$err];
                    }else{
                        $t->commit();
                        return ['status'=>true,'msg'=>\yii::t('app','Success')];
                    }
                }else{
                    if(isset($err)){
                        \yii::$app->getSession()->addFlash('error',$err);
                    }else{
                        $t->commit();
                        \yii::$app->getSession()->setFlash('success',\yii::t('app','Success'));
                        return $this->redirect(['index']);
                    }
                }
            }

        }else{
            return $this->redirect(['create']);
        }

        return $this->render('index',['admin'=>$admin,'info'=>$info]);
    }

    public function actionCreate(){
        $request=\yii::$app->request;
        $admin=Admin::findOne(\yii::$app->user->id);
        $admin->setScenario('info');
        $info=new AdminInfo();
        $info->loadDefaultValues();
        if($request->isPost ){
            $t=\yii::$app->db->beginTransaction();
            if( !($admin->load($request->post()) && $admin->save())){
                $err=ModelHelper::getErrorAsString($admin->getErrors());
                $t->rollBack();
            }
            $info->admin_id=$admin->id;
            if( !($info->load($request->post()) && $info->save())){
                $err=ModelHelper::getErrorAsString($info->getErrors());
                $t->rollBack();
            }
            if($request->isAjax){
                if(isset($err)){
                    return ['status'=>false,'msg'=>$err];
                }else{
                    return ['status'=>true,'msg'=>\yii::t('app','Success')];
                }
            }else{
                if(isset($err)){
                    \yii::$app->getSession()->addFlash('error',$err);
                }else{
                    \yii::$app->getSession()->addFlash('success',\yii::t('app','Success'));
                    return $this->redirect(['index']);
                }
            }
        }

        return $this->render('create',['admin'=>$admin,'info'=>$info]);

    }

}
