<?php

namespace backend\modules\admin\controllers;

use backend\components\actions\CreateAction;
use common\models\data\AdminInfo;
use yii\web\Controller;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{

    public function actions()
    {
        return [
            'create' => [
                'class' => CreateAction::className(),
                'modelClass' => AdminInfo::className(),
            ],
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $model=AdminInfo::find()->where(['admin_id'=>\yii::$app->getUser()->id])->with('admin')->one();
        if($model){

        }else{
            return $this->redirect(['create']);
        }

        return $this->render('index',['model'=>$model]);
    }
}
