<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace common\components\behaviors;

use common\components\events\LoginEvent;
use yii\base\Behavior;
use yii\base\Model;
/**
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @author Alexander Kochetov <creocoder@gmail.com>
 * @since 2.0
 */
class LimitLogin extends Behavior
{
    public $cache;


    public function events()
    {
        return [
            LoginEvent::EVENT_BEFORE_LOGIN=>'checkLogin',
            LoginEvent::EVENT_FAILED_LOGIN=>'failedLogin',
        ]; // TODO: Change the autogenerated stub
    }

    public function failedLogin($event){
        $owner = $event->sender;

    }

}
