<?php
namespace backend\models;

use Yii;
use yii\behaviors\AttributeBehavior;
use yii\db\ActiveRecord;
use common\models\data\Options as DateOptions;
/**
* This is the data class for [[common\models\database\Options]].
*
* @see \common\models\database\Options
*/
class CustomOptions extends DateOptions
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(),[
            'custom'=>[
                'class' =>AttributeBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_VALIDATE =>'type',
                    ActiveRecord::EVENT_BEFORE_INSERT =>'type',
                    ActiveRecord::EVENT_BEFORE_UPDATE =>'type',
                ],
                'value'=>self::OPTIONS_TYPE_SELF,
            ],
        ]); // TODO: Change the autogenerated stub
    }
}
